version: "3.3"

services:
  node-map:
    build: .
    labels:
      - traefik.http.middlewares.corsheader.headers.accessControlAllowOriginList=*
      - traefik.http.routers.node-map.middlewares=corsheader
      - traefik.http.routers.node-map.entrypoints=websecure
      - traefik.http.routers.node-map.rule=Host(`map.notrustverify.ch`)
      - traefik.http.routers.node-map.tls=true
      - traefik.http.routers.node-map.tls.certresolver=letsEncrypt
      - traefik.enable=true
    restart: unless-stopped
    env_file: .env
    ports:
      - "5005:5002"
    networks:
      - traefik-proxy
    volumes:
      - ./data/data.db:/data/data.db

networks:
   traefik-proxy:
      external: true

